#!/usr/bin/env zsh

# input format:
# line <- <name> ":=" (<name>|<atom>)("," (<name>|<atom>))*
# name <- "$"<atom>

function pre() {
	rm -f .includefiles
	awk '/^#include/ { print $2 > ".includefiles" } { if(index($1, "#")!=1) { print } } '
	if [[ -e .includefiles ]] ; then
		cat $(cat .includefiles) | pre
	fi
}

if [[ $# -gt 0 ]] ; then
	cat "$@" | $0
	exit
fi

pre | 
	sed '
		s/:=/,:=,/;
		s/\\,/%%COMMA%%/g;
		s/\\{/%%LBRACK%%/g;
		s/\\}/%%RBRACK%%/g' | awk '
	BEGIN { 
		print "#!/usr/bin/env python"

		# necessary for python2 compat if we have unicode input
		print "# coding=UTF-8"

		print ""
		print "# This code was generated by GGC (http://github.com/enkiv2/ggc), the Generative Grammar Compiler"
		print ""

		print "from random import Random"
		print "random=Random()\n" 

		FS=","
	}
	{
		if($2==":=") {
			# cachedItemsDummy pre-allocates blank variable names for cached items, 
			# to trick python.
			# Otherwise, references to the cached variables are assumed to be undefined 
			# at run-time when really they are only undefined at definition time
			cachedItemsDummy=cachedItemsDummy "\ncached_" $1 "=\"\""

			# cachedItems, on the other hand, is the actual cached representation,
			# which is currently created for every named rule, regardless of whether or
			# not it is used. In the future we could use an extra pass to eliminate
			# unused cached values, in order to speed up execution
			cachedItems=cachedItems "\ncached_" $1 "=" $1 "()"

			# cachedList is just a list of the cached values thus far, for use in defining
			# globals. It might not be required.
			cachedList=cachedList cSep "cached_"$1
			cSep=","

			if(!first) {
				first=$1
			}

			ret=ret "\ndef " $1 "():"
			ret=ret "\n\tglobal " cachedList ""
			ret=ret "\n\treturn random.choice(["
			for (i=3; i<=NF; i++) {
				ret = ret sep "\"" $i "\""
				sep="," 
			}
			ret=ret "])"
		}
	}
	END {
		print cachedItemsDummy
		print ret
		print cachedItems
		print "print(" first "())"
	}' | sed '
		s/\$\$\([a-zA-Z0-9_][a-zA-Z0-9_]*\)/"+cached_\1+\"/g;
		s/\$\([a-zA-Z0-9_][a-zA-Z0-9_]*\)/"+\1()+\"/g;
		s/{/\"+random.choice(["/g;s/}/"])+"/g;
		s/\[,/[/;s/%%COMMA%%/,/g;
		s/%%LBRACK%%/{/g;
		s/%%RBRACK%%/}/g'

